In [1]:
import numpy as np

In [2]:
a= np.array([10,20,30])
b=np.array([40,50,60])
np.concatenate((a,b))

array([10, 20, 30, 40, 50, 60])

In [3]:
a = np.array([[10,20],
              [30,40]])

b = np.array([[50,60],
              [70,80]])

np.concatenate((a,b))

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [4]:
np.concatenate((a,b),axis=1)

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])

In [5]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [6]:
a = np.array([[10, 20],
              [30, 40]])

b = np.array([[50, 60],
              [70, 80]])
np.concatenate((a,b),axis=0)
np.concatenate((a,b),axis=1)

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])

In [7]:
np.concatenate((a,b),axis=0)

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [8]:
a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6],
              [7,8]])

np.vstack((a,b))


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [9]:
a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6],
              [7,8]])

np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [10]:
arr = np.array([10,20,30,40,50,60])

np.split(arr, 3)

[array([10, 20]), array([30, 40]), array([50, 60])]

In [11]:
arr = np.array([10,20,30,40,50,60])

np.split(arr, 2)


[array([10, 20, 30]), array([40, 50, 60])]

In [12]:
arr = np.array([10,20,30,40,50,60,70,80])

np.split(arr, 4)

[array([10, 20]), array([30, 40]), array([50, 60]), array([70, 80])]

In [13]:
arr = np.array([[1,2],
                [3,4],
                [5,6],
                [7,8]])

np.split(arr, 2)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [14]:
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [15]:
np.split(arr, 2, axis=1)


[array([[1],
        [3],
        [5],
        [7]]),
 array([[2],
        [4],
        [6],
        [8]])]

In [16]:
np.split(arr, 2, axis=0)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [17]:
arr = np.array([50, 10, 40, 20, 30])

np.sort(arr)


array([10, 20, 30, 40, 50])

In [18]:
arr = np.array([50, 10, 40, 20, 30])

np.argsort(arr)

array([1, 3, 4, 2, 0])

In [19]:
arr = np.array([30, 10, 20])
np.argsort(arr)

array([1, 2, 0])

In [20]:
arr = np.array([30, 10, 50, 20, 40])

np.argmax(arr)


np.int64(2)