In [1]:
import numpy as np

In [2]:
arr = np.array([15, 28, 35, 42, 57, 63, 78, 91])
arr[(arr>=30)&(arr<=70)]

array([35, 42, 57, 63])

In [3]:
arr = np.array([10, 20, 30, 40, 50])
arr*2

array([ 20,  40,  60,  80, 100])

In [6]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
arr[:3,1]

array([20, 50, 80])

In [7]:
marks = np.array([
    [78, 85, 92],
    [65, 72, 80],
    [90, 88, 95],
    [55, 60, 70]
])
np.max(marks,axis=1)

array([92, 80, 95, 70])

In [8]:
np.min(marks,axis=1)

array([78, 65, 88, 55])

In [10]:
sales = np.array([
    [100, 150, 200],
    [250, 300, 350],
    [120, 180, 220]
])

np.sum(sales,axis=0)

array([470, 630, 770])

In [11]:
arr = np.array([10, 20, 30, 40, 50, 60])
arr.reshape(3,2)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [12]:
marks = np.array([45, 67, 23, 89, 56, 91, 34, 76])
a=marks[marks>60]

In [13]:
np.mean(a)

np.float64(80.75)

In [14]:
a

array([67, 89, 91, 76])

In [15]:
np.max(a)

np.int64(91)