In [1]:
import numpy as np

In [2]:
sales = np.array([
    [120, 150, 180],
    [200, 170, 220],
    [90,  130, 160],
    [250, 300, 280]
])

a=np.sum(sales,axis=1)

In [3]:
np.argmax(a)

np.int64(3)

In [4]:
a

array([450, 590, 380, 830])

In [5]:
marks = np.array([
    [78, 85, 92],
    [65, 72, 80],
    [90, 88, 95],
    [55, 60, 70],
    [82, 91, 87]
])
np.mean(marks,axis=0)

array([74. , 79.2, 84.8])

In [22]:
temperature = np.array([32, 35, 31, 38, 40, 29, 36, 34])
a=np.count_nonzero(temperature>35)

In [23]:
np.mean(a)

np.float64(3.0)

In [8]:
salary = np.array([25000, 32000, 18000, 45000, 28000, 52000, 21000])
salary[salary>30000]

array([32000, 45000, 52000])

In [21]:
np.max(salary)

np.int64(52000)

In [10]:
sales = np.array([
    [100, 200, 150, 300],
    [250, 180, 220, 350],
    [120, 300, 200, 280]
])
a=np.sum(sales,axis=0)

In [11]:
a

array([470, 680, 570, 930])

In [12]:
np.argmax(a)

np.int64(3)

In [13]:
X = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

w = np.array([10, 20])

In [14]:
np.dot(X,w)

array([ 50, 110, 170])

In [15]:
X = np.array([
    [10, 20],
    [30, 40],
    [50, 60]
])


In [16]:
marks = np.array([40, 50, 60, 70, 80, 90])
a=np.mean(marks)
np.std(a)

np.float64(0.0)

In [17]:
X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

w = np.array([0.5, 1, 2])


In [20]:

np.sum(X@w)

np.float64(57.0)

In [24]:
temperature = np.array([32, 35, 31, 38, 40, 29, 36, 34])
a=np.count_nonzero(temperature>35)

In [25]:
a

np.int64(3)

In [26]:
np.mean(a)

np.float64(3.0)