In [1]:
import numpy as np

In [2]:
arr = np.array([12, 45, 67, 23, 89, 34, 90, 56])
arr[arr>50]

array([67, 89, 90, 56])

In [3]:
arr = np.array([10, 25, 40, 55, 70, 85, 100])
arr[(arr>25)&(arr<85)]

array([40, 55, 70])

In [4]:
arr = np.array([15, 20, 35, 40, 55, 60])
arr[arr<25]=0
arr

array([ 0,  0, 35, 40, 55, 60])

In [5]:
arr = np.array([10, 20, 30, 40, 50])
arr+5

array([15, 25, 35, 45, 55])

In [6]:
marks = np.array([
    [78, 85, 92],
    [65, 72, 80],
    [90, 88, 95],
    [55, 60, 70]
])
np.sum(marks,axis=1)

array([255, 217, 273, 185])

In [7]:
np.mean(marks,axis=1)

array([85.        , 72.33333333, 91.        , 61.66666667])

In [10]:
sales = np.array([
    [100, 200, 150],
    [300, 250, 400],
    [120, 180, 160],
    [500, 450, 550]
])
a=np.sum(sales,axis=1)

In [11]:
np.argmax(a)

np.int64(3)

In [12]:
arr = np.array([5, 10, 15, 20, 25])
np.cumsum(arr)

array([ 5, 15, 30, 50, 75])

In [13]:
arr = np.array([10, 20, 10, 30, 20, 10, 40, 30])
np.unique(arr,return_counts=True)

(array([10, 20, 30, 40]), array([3, 2, 2, 1]))

In [14]:
marks = np.array([35, 78, 92, 41, 66, 28, 85, 55, 73, 90])
a=marks[marks>60]

In [15]:
a

array([78, 92, 66, 85, 73, 90])

In [16]:
np.count_nonzero(a)

np.int64(6)

In [19]:
arr = np.array([15, 20, 35, 40, 55, 60])
np.where(arr<40,0,arr)

array([ 0,  0,  0, 40, 55, 60])