In [1]:
import numpy as np

In [2]:
marks=np.array([35, 78, 92, 41, 66, 28, 85, 55, 73, 90])

In [3]:
marks[marks>60]

array([78, 92, 66, 85, 73, 90])

In [4]:
marks = np.array([35, 78, 92, 41, 66, 28, 85, 55, 73, 90])
marks[(marks>50)&(marks<80)]

array([78, 66, 55, 73])

In [5]:
marks = np.array([35, 78, 92, 41, 66, 28, 85, 55, 73, 90])
marks[(marks>70) | (marks<40)]

array([35, 78, 92, 28, 85, 73, 90])

In [6]:
marks[marks>79]

array([92, 85, 90])

In [7]:
marks<60
marks[marks<60]=0

In [8]:
marks

array([ 0, 78, 92,  0, 66,  0, 85,  0, 73, 90])

In [9]:
marks = np.array([45, 67, 23, 89, 56, 91, 34, 76])
marks[marks>70]=100

In [10]:
marks


array([ 45,  67,  23, 100,  56, 100,  34, 100])

In [11]:
marks = np.array([45, 67, 23, 89, 56, 91, 34, 76])
marks[(marks>60) & (marks<90)]

array([67, 89, 76])

In [12]:
marks = np.array([
    [78, 85, 92],
    [65, 72, 80],
    [90, 88, 95],
    [55, 60, 70]
])
np.mean(marks,axis=1)

array([85.        , 72.33333333, 91.        , 61.66666667])

In [13]:
marks = np.array([
    [78, 85, 92],
    [65, 72, 80],
    [90, 88, 95],
    [55, 60, 70]
])
np.mean(marks,0)

array([72.  , 76.25, 84.25])

In [14]:
marks = np.array([
    [78, 85, 92],
    [65, 72, 80],
    [90, 88, 95],
    [55, 60, 70]
])

a=np.sum(marks,axis=1)

In [15]:
np.max(a)

np.int64(273)

In [16]:
np.argmax(a)

np.int64(2)

In [17]:
marks = np.array([
    [78, 85, 92],
    [65, 72, 80],
    [90, 88, 95],
    [55, 60, 70]
])


In [18]:
np.count_nonzero(marks>75,axis=0)

array([2, 2, 3])

In [26]:
sales = np.array([
    [100, 200, 150],
    [300, 250, 400],
    [120, 180, 160],
    [500, 450, 550]
])
a=np.sum(sales,axis=1)

In [27]:
a


array([ 450,  950,  460, 1500])

In [28]:
np.argmax(a)

np.int64(3)

In [30]:
sales = np.array([
    [100, 200, 150],
    [300, 250, 400],
    [120, 180, 160],
    [500, 450, 550]
])
a=sales[sales<200]=0

In [32]:
sales

array([[  0, 200,   0],
       [300, 250, 400],
       [  0,   0,   0],
       [500, 450, 550]])

In [40]:
marks = np.array([35, 67, 23, 89, 56, 91, 34, 76])
np.where(marks<60,0,marks)

array([ 0, 67,  0, 89,  0, 91,  0, 76])

In [41]:
np.where(marks>=60,"pass","fail")

array(['fail', 'pass', 'fail', 'pass', 'fail', 'pass', 'fail', 'pass'],
      dtype='<U4')

mar

In [42]:
arr = np.array([10, 20, 10, 30, 20, 10, 40, 30, 20])

In [46]:

np.unique(arr,return_counts=True)

(array([10, 20, 30, 40]), array([3, 3, 2, 1]))

In [47]:
marks = np.array([25, 45, 67, 89, 105, 120, 56])
np.clip(marks,40,100)

array([ 40,  45,  67,  89, 100, 100,  56])

In [48]:
sales = np.array([
    [100, 200, 300],
    [150, 250, 350],
    [200, 300, 400]
])

In [49]:
np.sum(sales,axis=0)

array([ 450,  750, 1050])

In [50]:
np.sum(sales,axis=1)

array([600, 750, 900])

In [51]:
np.argmax(sales)

np.int64(8)

In [52]:
sales = np.array([100, 150, 200, 250, 300])
np.cumsum(sales)

array([ 100,  250,  450,  700, 1000])

In [53]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
np.transpose(arr)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [57]:
marks = np.array([
    [78, 85, 92],
    [65, 72, 80],
    [90, 88, 95],
    [55, 60, 70],
    [82, 91, 87]
])
a=np.sum(marks,axis=1)

In [58]:
a

array([255, 217, 273, 185, 260])

In [59]:
np.argmax(a)

np.int64(2)