In [1]:
import numpy as np

In [2]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
arr[1,1]

np.int64(50)

In [4]:
arr[0]

array([10, 20, 30])

In [6]:
arr[:,1]

array([20, 50, 80])

In [9]:
arr[2,1:3]

array([80, 90])

In [19]:
arr[0:2,1:3]

array([[20, 30],
       [50, 60]])

In [21]:
arr[:,[0,2]]

array([[10, 30],
       [40, 60],
       [70, 90]])

In [31]:
arr[0:2,[0,1]]

array([[10, 20],
       [40, 50]])

In [32]:
arr[:3,[2]]

array([[30],
       [60],
       [90]])

In [33]:
a = np.array([10, 20, 30])
b = np.array([40, 50, 60])
np.concatenate(a,b)

TypeError: only integer scalar arrays can be converted to a scalar index