In [1]:
import numpy as np

In [2]:
arr = np.array([45, 12, 89, 23, 67, 10])

In [3]:
np.sort(arr)

array([10, 12, 23, 45, 67, 89])

In [4]:
np.sort(arr)[::-1]

array([89, 67, 45, 23, 12, 10])

In [5]:
arr2 = np.array([30, 10, 50, 20, 40])

In [6]:
np.sort(arr2)

array([10, 20, 30, 40, 50])

In [7]:
variable=np.sort(arr2)

In [8]:
variable

array([10, 20, 30, 40, 50])

In [9]:
arr3 = np.array([40, 10, 30, 20])

In [10]:
np.sort(arr3)

array([10, 20, 30, 40])

In [11]:
arr3.dtype

dtype('int64')