In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(6,10)

array([10, 10, 10, 10, 10, 10])

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
np.linspace(0,100,6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [18]:
arr=np.array([1,2,3,4,5,6])

In [27]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
arr2=np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120])

In [29]:
arr2.reshape(3,4)

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])