In [2]:
import numpy as np

In [3]:
arr=np.array([10,20,30,40,50])

In [4]:
arr+10

array([20, 30, 40, 50, 60])

In [5]:
arr-5

array([ 5, 15, 25, 35, 45])

In [6]:
arr*2

array([ 20,  40,  60,  80, 100])

In [7]:
arr/10

array([1., 2., 3., 4., 5.])

In [8]:
a=np.array([10,20,30,40])

In [9]:
b=np.array([1,2,3,4])

In [10]:
a+b

array([11, 22, 33, 44])

In [11]:
a-b

array([ 9, 18, 27, 36])

In [12]:
a*b

array([ 10,  40,  90, 160])

In [13]:
a/b

array([10., 10., 10., 10.])

In [14]:
c=np.array([10,25,30,45,50])

In [15]:
c>30

array([False, False, False,  True,  True])

In [16]:
np.sum(arr)

np.int64(150)

In [17]:
np.mean(arr)

np.float64(30.0)

In [18]:
np.max(arr)

np.int64(50)

In [19]:
np.min(arr)

np.int64(10)