In [2]:
import numpy as np

In [6]:
arr=np.array([10,20,30,40,50])

In [7]:
arr[2]

np.int64(30)

In [9]:
arr[4]

np.int64(50)

In [11]:
arr[-2]

np.int64(40)

In [12]:
arr[-5]

np.int64(10)

In [16]:
arr2=np.array([5,10,15,20,25,30])

In [35]:
arr2[1:4]

array([10, 15, 20])

In [36]:
arr2[2:]

array([15, 20, 25, 30])

In [37]:
arr2[3]

np.int64(20)

In [21]:
arr2[2]

np.int64(15)

In [22]:
arr2[3]

np.int64(20)

In [23]:
arr2[4]

np.int64(25)

In [24]:
arr2[5]

np.int64(30)

In [25]:
tdarray=np.array([[10,20,30],[40,50,60],[70,80,90]])

In [27]:
tdarray[1,1]

np.int64(50)

In [28]:
tdarray[2,0]

np.int64(70)

In [30]:
tdarray[:,1]

array([20, 50, 80])

In [33]:
tdarray[1,0:4]

array([40, 50, 60])