In [2]:
import numpy as np

In [3]:
arr = np.array([5, 10, 5, 20, 10, 30, 5, 20])

In [4]:
np.unique(arr)

array([ 5, 10, 20, 30])

In [5]:
np.unique(arr, return_counts=True)

(array([ 5, 10, 20, 30]), array([3, 2, 2, 1]))

In [6]:
arr = np.array([10, 20, 30, 40, 50])

np.where(arr > 25)

(array([2, 3, 4]),)