In [1]:
import numpy as np

In [2]:
a = np.array([[10,20,30],
              [40,50,60]])

b = np.array([1,2,3])

a + b

array([[11, 22, 33],
       [41, 52, 63]])

In [3]:
a = np.array([[10,20,30],
              [40,50,60]])

b = np.array([10,20,30])

a * b

array([[ 100,  400,  900],
       [ 400, 1000, 1800]])

In [4]:
a = np.array([[10,20,30],
              [40,50,60]])

b = np.array([[1],
              [2]])

a + b

array([[11, 21, 31],
       [42, 52, 62]])

In [5]:
a = np.array([[10,20,30],
              [40,50,60]])

b = np.array([[2],
              [3]])
a*b

array([[ 20,  40,  60],
       [120, 150, 180]])

In [6]:
marks = np.array([[50, 60, 70],
                  [40, 55, 65],
                  [80, 75, 90]])

bonus = np.array([5, 10, 15])
marks+bonus

array([[ 55,  70,  85],
       [ 45,  65,  80],
       [ 85,  85, 105]])

In [7]:
prices = np.array([[100, 200, 300],
                   [400, 500, 600]])

discount = np.array([[10],
                     [20]])
prices-discount

array([[ 90, 190, 290],
       [380, 480, 580]])

In [8]:
arr = np.array([1,2,3,4,5,6])

arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr = np.array([10,20,30,40,50,60,70,80,90,100,110,120])
arr.reshape(3,4)

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [11]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
arr = np.array([[1,2,3],
                [4,5,6]])
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
arr = np.array([[10,20,30],
                [40,50,60]])
arr.reshape(1,6)

array([[10, 20, 30, 40, 50, 60]])

In [21]:
arr = np.array([[10,20,30],
                [40,50,60]])

arr.flatten()

array([10, 20, 30, 40, 50, 60])

In [22]:
arr = np.array([[10,20,30],
                [40,50,60]])

arr.ravel()

array([10, 20, 30, 40, 50, 60])

In [ ]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
