In [1]:
import numpy as np

In [2]:
arr=np.array([[10,20,30],[40,50,60]])

In [3]:
np.sum(arr,axis=0)

array([50, 70, 90])

In [4]:
np.sum(arr,axis=1)

array([ 60, 150])

In [5]:
np.mean(arr,axis=0)

array([25., 35., 45.])

In [9]:
np.max(arr,axis=1)

array([30, 60])

In [8]:
np.min(arr,axis=0)

array([10, 20, 30])