In [1]:
import numpy as np

In [2]:
arr = np.array([10, np.nan, 30, np.nan, 50])

np.isnan(arr)

array([False,  True, False,  True, False])

In [3]:
arr = np.array([10, np.inf, 30, -np.inf, 50])

np.isinf(arr)

array([False,  True, False,  True, False])

In [4]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

np.dot(a, b)

array([[19, 22],
       [43, 50]])

In [6]:
arr = np.array([
    [10, 20],
    [30, 40],
    [50, 60]
])
np.transpose(arr)

array([[10, 30, 50],
       [20, 40, 60]])

In [7]:
arr.T

array([[10, 30, 50],
       [20, 40, 60]])

In [8]:
arr = np.array([10, 20, 30, 40, 50])

np.sum(arr)

np.int64(150)

In [9]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

In [12]:
np.sum(arr,axis=1)

array([ 60, 150])

In [13]:
np.sum(arr,axis=0)

array([50, 70, 90])

In [14]:
arr = np.array([10, 20, 30, 40, 50])

np.mean(arr)

np.float64(30.0)

In [15]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
np.mean(arr,axis=0)

array([25., 35., 45.])

In [16]:
np.mean(arr,axis=1)

array([20., 50.])

In [17]:
arr = np.array([10, 20, 30, 40, 50])

np.var(arr)


np.float64(200.0)

In [18]:
arr = np.array([10, 20, 30, 40])
np.cumsum(arr)

array([ 10,  30,  60, 100])

In [19]:
arr = np.array([5, 10, 15, 20, 25])
np.cumsum(arr)

array([ 5, 15, 30, 50, 75])

In [20]:
arr = np.array([2, 3, 4, 5, 6])
np.cumprod(arr)

array([  2,   6,  24, 120, 720])