In [1]:
import numpy as np

In [3]:
arr=np.array([[1,2,34,5,]],np.int64)

In [4]:
arr

array([[ 1,  2, 34,  5]])

In [5]:
arr.dtype


dtype('int64')

In [7]:
arr.shape


(1, 4)

In [8]:
arr[0,3]

np.int64(5)

In [9]:
arr[0,3]=23

In [10]:
arr

array([[ 1,  2, 34, 23]])

In [12]:
zer=np.zeros((3,5))

In [13]:
zer

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
ide=np.identity(10)

In [15]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [17]:
emp=np.empty([9,6])

In [18]:
emp

array([[ 3.29625577e-315,  0.00000000e+000,  1.94661864e-321,
        -8.16999161e+043,  2.50535190e-292,  5.28489842e-308],
       [ 2.59049586e-317,  0.00000000e+000,  4.89516249e-307,
         3.95252517e-322,  0.00000000e+000, -2.77860530e-162],
       [ 1.52918452e-297,  0.00000000e+000,  0.00000000e+000,
         1.25623258e-311,  0.00000000e+000,  0.00000000e+000],
       [ 6.39842420e-308,  1.02187024e+296,  4.89526774e-307,
         5.45448473e-321,  0.00000000e+000,  6.56940084e-288],
       [ 0.00000000e+000,  0.00000000e+000,  9.84301630e-303,
         1.92685602e-322,  4.31114002e-308,  5.23246457e-316],
       [ 0.00000000e+000,  3.20809369e-302,  7.98410084e-321,
         0.00000000e+000,  3.92314582e-310,  1.26293999e-317],
       [ 3.89387974e-308,  4.51560983e-311,  0.00000000e+000,
         0.00000000e+000,  6.89028643e-316,  0.00000000e+000],
       [ 8.16677681e+039,  8.27680353e-313,  1.43362036e-310,
         5.20354528e-259,  0.00000000e+000,  0.00000000e+000],


In [19]:
emp_like= np.empty_like(arr)

In [20]:
emp_like

array([[673248597,         0, 672878416, 672041680]])

In [23]:
rng=np.arange(6)

In [24]:
rng


array([0, 1, 2, 3, 4, 5])