In [2]:
import numpy as np

In [3]:
arr = np.array([10, 20,30,40,50])

In [4]:
arr+10

array([20, 30, 40, 50, 60])

In [5]:
arr-5

array([ 5, 15, 25, 35, 45])

In [6]:
arr*3

array([ 30,  60,  90, 120, 150])

In [7]:
arr/5

array([ 2.,  4.,  6.,  8., 10.])

In [8]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

In [9]:
a+b

array([11, 22, 33])

In [10]:
a*b

array([10, 40, 90])

In [11]:
a/b

array([10., 10., 10.])

In [12]:
arr = np.array([[10, 20, 30],
                [40, 50, 60]])

In [14]:
arr+5

array([[15, 25, 35],
       [45, 55, 65]])

In [15]:
arr+b

array([[11, 22, 33],
       [41, 52, 63]])

In [16]:
arr*b

array([[ 10,  40,  90],
       [ 40, 100, 180]])

In [17]:
arr/b

array([[10., 10., 10.],
       [40., 25., 20.]])

In [18]:
a = np.array([[10, 20, 30],
              [40, 50, 60]])

b = np.array([1, 2])

In [19]:
a+b

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 