In [1]:
import numpy as np

In [2]:
numbers=np.array([10,20,30,40,50])

In [3]:
numbers

array([10, 20, 30, 40, 50])

In [4]:
nu=np.array([5,15,25,35,45])

In [5]:
myarr=np.array([100,200,300,400,500])

In [6]:
myarr

array([100, 200, 300, 400, 500])

In [7]:
salary=np.array([25000, 30000, 28000, 35000, 40000])

In [8]:
rng=np.arange (1,11)

In [9]:
rng

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
typ=np.array([50,60,70,80])

In [11]:
typ.dtype

dtype('int64')

In [12]:
oarry=np.array([10,20,30])
tarry=np.array([[40,50,60]])

In [13]:
oarry


array([10, 20, 30])

In [14]:
tarry

array([[40, 50, 60]])

In [15]:
myfavarr=np.array([1,2,3,4,5])

myfavarr

In [16]:
myfavarr

array([1, 2, 3, 4, 5])

In [17]:
stdmarks=np.array([78,65,89,45,92])

In [18]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11])

In [19]:
arr1=np.array([10,20,30])
arr2=np.array([40,50,60])

In [20]:
mynum=np.array([1,2,3,4,5])

In [21]:
x=[10,20,30,40,50]

In [22]:
arr=np.array(x)

In [23]:
arr.ndim

1

In [24]:
arr.size

5

In [25]:
arr.dtype

dtype('int64')

In [26]:
tdarr=np.array([[1,2,3],[4,5,6]])

In [27]:
tdarr.shape

(2, 3)

In [28]:
tdarr.ndim

1

In [29]:
tdarr.size

5

In [30]:
arra=np.array([[10, 20],
 [30, 40],
 [50, 60]])


In [31]:
arra.shape

(3, 2)

In [32]:
arra.size

6

In [33]:
aray=np.array([[1, 2, 3, 4],
 [5, 6, 7, 8]])

In [34]:
aray.shape

(2, 4)

In [35]:
aray.ndim

2

In [36]:
aray.size

8

In [37]:
aray.dtype

dtype('int64')

In [38]:
my_array=np.array([[1,2,3,4],[11,22,33,44]])

In [39]:
my_array.shape

(2, 4)

In [40]:
my_array.ndim

2

In [41]:
my_array.size

8

In [42]:
my_array.dtype

dtype('int64')

In [43]:
tdarr = np.array([[1, 2, 3],
                  [4, 5, 6]])

In [44]:
tdarr.shape

(2, 3)

In [45]:
tdarr.ndim

2

In [46]:
tdarr.size

6